### ISSUE TITLE
Update to `@mdn/browser-compat-data` v5

### ISSUE THREAD

**Issue by sgomes** [wessberg/browserslist-generator#10]
Looks like `@mdn/browser-compat-data` is now on major version 5, which means that `browserslist-generator` unfortunately is stuck with older versions (about 6 months old now), since it depends on `^4.1.16`.

Updating `package.json` to use v5 (and making the necessary changes if the new major version comes with any breaking changes for `browserslist-generator`) would allow consumers to keep using up-to-date versions of `browserslist-generator` as needed.

I'll take a look at putting together a PR, but I wanted to create the issue first in case I take too long or need to pull back!

**Comment by wessberg** [comment]
Hi there.
Sorry for the late reply. I went ahead and added migrated to v5 of @mdn/browser-compat-data recently in v2.0. Thanks!

**Comment by sgomes** [comment]
Thank you so much for making the change and for updating this issue, @wessberg! 👍
