### ISSUE TITLE
ChromeAndroid in the browerslist query always results in ECMA version `es3`

### ISSUE THREAD

**Issue by alexanbj** [wessberg/browserslist-generator#3]
I noticed that if you specify `and_chr` in the browserslist query, `getAppropriateEcmaVersionForBrowserslist` will always return `es3`.

Here is a codesandbox that demonstrates this: https://codesandbox.io/s/ecstatic-silence-ey2g2

**Comment by wessberg** [comment]
Hi there. Thanks for reporting this issue. It has been fixed in [v1.0.30](https://github.com/wessberg/browserslist-generator/releases/tag/v1.0.30)
