### ISSUE TITLE
Bump browserslist to >= 4.13.0 to support the 'supports' query

### ISSUE THREAD

**Issue by ggoodman** [wessberg/browserslist-generator#5]
I would like to use a `browserslist` config in a rollup project using your `@wessberg/rollup-plugin-ts` and traced things back here when I realized the query was unsupported in the pinned version.

Please consider bumping to `>=4.13.0`. See [the changelog](https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#413) for what this brings.

Cheers!

**Comment by wessberg** [comment]
Cool, thanks for the heads up! I should probably consider making it a `peerDependency` in the next major version 🙂

**Comment by wessberg** [comment]
The dependency has been bumped in the [latest version](https://github.com/wessberg/browserslist-generator/releases/tag/v1.0.38)
